Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false


  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.64.15"
    master.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install php-geshi -y
    cd /var/www/html
    sudo wget https://download.dokuwiki.org/out/dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo tar -xvf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm -Rf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm index.html
    cd dokuwiki/
    sudo mv * ../
    sudo chown -R vagrant:www-data /var/www/html/
    sudo chown -R vagrant:www-data /etc/apache2/
    SHELL
    master.vm.provision "file", source: "files/wiki.lab.local.conf", destination: "/etc/apache2/sites-available/wiki.lab.local.conf"
    master.vm.provision "shell", inline: <<-SHELL
    sudo a2ensite wiki.lab.local
    sudo systemctl reload apache2
  SHELL
    
  end

  config.vm.define "backup" do |backup|
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "192.168.64.16"
    backup.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install php-geshi -y
    cd /var/www/html
    sudo wget https://download.dokuwiki.org/out/dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo tar -xvf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm -Rf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm index.html
    cd dokuwiki/
    sudo mv * ../
    sudo chown -R vagrant:www-data /var/www/html/
    sudo chown -R vagrant:www-data /etc/apache2/
    SHELL
    backup.vm.provision "file", source: "files/wiki.lab.local.conf", destination: "/etc/apache2/sites-available/wiki.lab.local.conf"
    backup.vm.provision "shell", inline: <<-SHELL
    sudo a2ensite wiki.lab.local
    sudo systemctl reload apache2
  SHELL
  end

  config.vm.define "reverse" do |reverse|
    reverse.vm.hostname = "reverse"
    reverse.vm.network "private_network", ip: "192.168.64.17"
    reverse.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install nginx -y
    sudo unlink /etc/nginx/sites-enabled/default
    SHELL
    backup.vm.provision "file", source: "files/reverse-proxy", destination: "/etc/apache2/sites-available/reverse-proxy"
    reverse.vm.provision "shell", inline: <<-SHELL
    sudo systemctl restart nginx
    SHELL
  end
end