Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.64.16"
    master.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update 
    sudo apt-get install dokuwiki -y
    sudo sed -i -e "s/127.0.0.1/All/g" /etc/dokuwiki/apache.conf
    sudo service apache2 reload
    SHELL
  end

  config.vm.define "backup" do |backup|
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "192.168.64.18"
    backup.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update 
    sudo apt-get install dokuwiki -y
    sudo sed -i -e "s/127.0.0.1/All/g" /etc/dokuwiki/apache.conf
    sudo service apache2 reload
    SHELL
  end
end